import Foundation

/// Verbatim port of `core/domain/model/AirlineDatabase.kt`.
enum AirlineDatabase {

    /// ICAO telephony prefix (first 3 chars of callsign) → Airline name.
    static let prefixToName: [String: String] = [
        "AAL": "American Airlines",
        "UAL": "United Airlines",
        "DAL": "Delta Air Lines",
        "SWA": "Southwest Airlines",
        "FDX": "FedEx",
        "UPS": "UPS Airlines",
        "SKW": "SkyWest Airlines",
        "ASA": "Alaska Airlines",
        "JBU": "JetBlue",
        "FFT": "Frontier Airlines",
        "NKS": "Spirit Airlines",
        "WJA": "WestJet",
        "AWI": "Air Wisconsin",
        "ENY": "Envoy Air",
        "RPA": "Republic Airways",
        "PDT": "Piedmont Airlines",
        "OPT": "PSA Airlines",
        "CPZ": "Comair",
        "GJS": "GoJet Airlines",
        "EJA": "NetJets",
        "FLG": "Endeavor Air",
        "ASH": "Mesa Airlines",
        "HAL": "Hawaiian Airlines",
        "SCX": "Sun Country",
        "GTI": "Atlas Air",
        "CLX": "Cargolux",
        "ABX": "ABX Air",
        "ATN": "Air Transport International",
        "NCB": "Northern Air Cargo",
        "POE": "Polar Air Cargo",
        "KAP": "Key Lime Air",
        "LXJ": "Flexjet",
        "VVI": "VistaJet",
        "XOJ": "XOJET",
        "CAW": "Cape Air",
        "SLQ": "Sloane Square Air",
        "TRS": "Trans States Airlines",
        "CHQ": "Chautauqua Airlines",
        "TFT": "Trans States Holdings",
        "RYR": "Ryanair",
        "BAW": "British Airways",
        "DLH": "Lufthansa",
        "AFR": "Air France",
        "KLM": "KLM Royal Dutch Airlines",
        "UAE": "Emirates",
        "QTR": "Qatar Airways",
        "ETH": "Ethiopian Airlines",
        "KAL": "Korean Air",
        "JAL": "Japan Airlines",
        "ANA": "All Nippon Airways",
        "CPA": "Cathay Pacific",
        "MXY": "Mexicana",
        "AMX": "Aeromexico",
        "ACA": "Air Canada",
        "VRD": "Virgin America",
        "BTA": "Boutique Air",
        "TOC": "Trans-Air Charters",
        "USA": "US Airways",
        "MID": "Midway Airlines",
        "WEN": "Wenceslas Air",
        "CWC": "Chalk's Ocean Airways",
        "GAP": "Aeromar",
        "AZA": "ITA Airways",
        "IBE": "Iberia",
        "VLG": "Vueling",
        "THY": "Turkish Airlines",
        "SVR": "Smartavia",
        "EZY": "easyJet",
        "WZZ": "Wizz Air",
        "TOM": "TUI Airways",
        "TCX": "Thomas Cook",
        "CFG": "Condor",
        "ICE": "Icelandair",
        "SAS": "Scandinavian Airlines",
        "FIN": "Finnair",
        "TAP": "TAP Air Portugal",
        "LHA": "Lufthansa",
        "CSN": "China Southern",
        "CCA": "Air China",
        "CES": "China Eastern",
        "HXA": "Hainan Airlines",
        "SIA": "Singapore Airlines",
        "MAS": "Malaysia Airlines",
        "THA": "Thai Airways",
        "GIA": "Garuda Indonesia",
        "AIC": "Air India",
        "RAM": "Royal Air Maroc",
        "MSR": "EgyptAir",
        "KQA": "Kenya Airways",
        "SAA": "South African Airways",
        "TAM": "LATAM Brasil",
        "LAN": "LATAM Airlines",
        "ARG": "Aerolíneas Argentinas",
        "GLO": "Gol Transportes Aéreos",
        "AZU": "Azul Brazilian Airlines",
        "CBJ": "Capital Cargo International",
        "FTH": "Freight",
        "ISS": "Islas Airways",
        "BSK": "Biszkek Air",
        "MVT": "Maverick Transportation",
        "STN": "Saturn Aviation",
        "PCA": "Private Charter",
        "CAL": "China Airlines",
        "EVA": "EVA Air",
        "OAL": "Olympic Air",
        "MSX": "Middle East Airlines",
        "QFA": "Qantas",
        "VOZ": "Virgin Australia",
        "JST": "Jetstar",
        "TGW": "Trans Global Airways",
        "EIN": "Aer Lingus",
        "SXS": "SATA Air Acores",
        "AVA": "Avianca",
        "PDV": "Perimeter Aviation",
        "AMF": "Air Mobility Command",
        "RCH": "Reach (USAF AMC)",
        "SAM": "Special Air Mission",
        "HKY": "Hawkeye",
        "MCE": "Med-Care",
        "LAF": "Life Flight",
        "SHB": "Shield Air",
        "TRP": "Tropic Air",
        "AFO": "Air Force One",
        "EGL": "Eagle Aviation",
        "PFT": "Proflight",
        "NTL": "Northern Lights",
        "STX": "St. Croix Aviation",
        "MIA": "Miami Air",
        "HZN": "Horizon Air",
        "QXE": "Horizon Air (IATA)",
        "SBN": "Sun Air",
        "IFS": "Iflyus",
        "CTG": "Chicago Express",
        "MEP": "Midwest Air",
        "MWA": "Midwest Airlines",
        "TXI": "Texas International",
        "IND": "Independence Air",
        "FSX": "FedEx Feeder",
        "ABD": "Air Atlanta",
        "WFS": "World Fuel Services",
        "TFL": "Arkefly",
        "AEA": "Air Europa",
        "VLN": "Volaris",
        "IGO": "IndiGo",
        "SEJ": "SpiceJet",
        "AXB": "Air India Express",
        "GOW": "Go First",
        "VOI": "Vistara",
        "SFJ": "Starflyer",
        "PEA": "People's Viennaline",
        "CXI": "Cayman Airways",
        "BWA": "Caribbean Airlines",
        "MPS": "Maputo Air",
        "EAL": "Eastern Air Lines",
        "NWA": "Northwest Airlines",
        "CCM": "Corse Med Aero",
        "TWA": "Trans World Airlines",
        "CFE": "BA CityFlyer",
        "CTH": "Cathy Dragon",
        "EWG": "Eurowings",
    ]

    /// `lookupCallsign` in AirlineDatabase.kt.
    /// Returns nil for nil/blank; otherwise trims, takes first 3 chars, uppercases, and looks up.
    static func name(forCallsign callsign: String?) -> String? {
        guard let callsign = callsign else { return nil }
        let trimmed = callsign.trimmingCharacters(in: .whitespaces)
        if trimmed.isEmpty { return nil }
        let prefix = String(trimmed.prefix(3)).uppercased()
        return prefixToName[prefix]
    }
}
